"""
Behavior Inference Engine (Phase 4).

Loads the declarative evidence-pattern library (rules/evidence_patterns.yaml)
and evaluates each rule against every relationship (edge) in the
knowledge graph. A rule match creates an InferredBehavior node with
explicit supporting-evidence references, a confidence score, and an
explanation path -- never free text generated by an LLM. This is the
component responsible for deciding "what happened"; Phase 5/6 (llm/explain.py)
is only ever responsible for describing it in natural language.

Future extensions (see Section III.F / Conclusion of the paper) may
replace or augment `match_rule` with a learned (GNN) scoring function
without changing the InferredBehavior interface consumed downstream.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import networkx as nx
import yaml

from .models import BehaviorConcept, InferredBehavior
from .graph_builder import add_behavior_node

logger = logging.getLogger(__name__)

DEFAULT_RULES_PATH = Path(__file__).parent / "rules" / "evidence_patterns.yaml"


@dataclass
class Rule:
    id: str
    edge_type: str
    produces: BehaviorConcept
    confidence: float
    description: str
    source_type: str | None = None
    target_type: str | None = None
    source_attr_patterns: dict[str, str] | None = None
    target_attr_patterns: dict[str, str] | None = None
    # Matches on which plugin produced the target artifact (Artifact.
    # source_plugin, stored as a top-level node attribute by
    # graph_builder.build_graph -- not inside target_attr_patterns'
    # `attributes` dict). Added to support rules like
    # code_injection_malfind_flagged, where the fact that a specific
    # plugin's own internal heuristics flagged an artifact IS the
    # evidence, independent of that artifact's raw attribute values.
    target_source_plugin: str | None = None

    @classmethod
    def from_dict(cls, d: dict[str, Any]) -> "Rule":
        return cls(
            id=d["id"],
            edge_type=d["edge_type"],
            produces=BehaviorConcept(d["produces"]),
            confidence=float(d["confidence"]),
            description=d["description"].strip(),
            source_type=d.get("source_type"),
            target_type=d.get("target_type"),
            source_attr_patterns=d.get("source_attr_patterns") or None,
            target_attr_patterns=d.get("target_attr_patterns") or None,
            target_source_plugin=d.get("target_source_plugin"),
        )


def load_rules(path: Path | str = DEFAULT_RULES_PATH) -> list[Rule]:
    with open(path, "r", encoding="utf-8") as f:
        raw = yaml.safe_load(f)
    return [Rule.from_dict(entry) for entry in raw]


def _attrs_match(attributes: dict[str, Any], patterns: dict[str, str] | None) -> bool:
    if not patterns:
        return True
    for attr_name, pattern in patterns.items():
        value = attributes.get(attr_name)
        if value is None:
            return False
        if not re.search(pattern, str(value)):
            return False
    return True


def match_rule(
    graph: nx.MultiDiGraph, rule: Rule, source: str, target: str, edge_data: dict
) -> bool:
    if edge_data.get("edge_type") != rule.edge_type:
        return False

    source_node = graph.nodes[source]
    target_node = graph.nodes[target]

    if rule.source_type and source_node.get("artifact_type") != rule.source_type:
        return False
    if rule.target_type and target_node.get("artifact_type") != rule.target_type:
        return False
    if rule.target_source_plugin and target_node.get("source_plugin") != rule.target_source_plugin:
        return False

    if not _attrs_match(source_node.get("attributes", {}), rule.source_attr_patterns):
        return False
    if not _attrs_match(target_node.get("attributes", {}), rule.target_attr_patterns):
        return False

    return True


def run_inference(
    graph: nx.MultiDiGraph, rules: list[Rule] | None = None
) -> list[InferredBehavior]:
    """
    Evaluate every rule against every relationship edge in the graph.
    For each match, create an InferredBehavior, attach it to the graph
    via `add_behavior_node`, and return the full list of behaviors
    produced during this run.
    """
    rules = rules if rules is not None else load_rules()
    behaviors: list[InferredBehavior] = []

    # Only iterate relationship edges (skip any evidence_for edges
    # that might already exist from a prior inference pass).
    edges = [
        (u, v, data)
        for u, v, data in graph.edges(data=True)
        if data.get("kind") == "relationship"
    ]

    for rule in rules:
        for source, target, edge_data in edges:
            if not match_rule(graph, rule, source, target, edge_data):
                continue

            behavior = InferredBehavior(
                behavior=rule.produces,
                rule_id=rule.id,
                supporting_artifact_ids=[source, target],
                supporting_relationship_ids=[f"{source}->{target}:{edge_data.get('edge_type')}"],
                confidence=rule.confidence,
                explanation_path=rule.description,
            )
            add_behavior_node(graph, behavior)
            behaviors.append(behavior)
            logger.info(
                "Rule '%s' matched: %s -[%s]-> %s => %s (confidence=%.2f)",
                rule.id, source, edge_data.get("edge_type"), target,
                rule.produces.value, rule.confidence,
            )

    return behaviors
